In [1]:
import numpy as np

In [2]:
# 1). Convert a Python list x=[1,2,3] into a Numpy array.
x = [1,2,3]

m = np.asarray(x)
type(m)

numpy.ndarray

In [3]:
# 2). Create an 2D array with shape of (3,2), filled with 6
np.full(shape=(3,2), fill_value=6)

array([[6, 6],
       [6, 6],
       [6, 6]])

In [4]:
# 3). Create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.
a = np.arange(start=2, stop=101, step=2)
print(a)
print("Mean = {}".format(a.mean()))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
Mean = 51.0


In [5]:
# 4). Create an 3x3x3 array filled with arbitrary values; and find the minimum and maximum values.
m = np.random.random(size=(3, 3, 3)) * 100
print(m)
print("Min: {}, Max: {}".format(m.min(), m.max()))

[[[75.85506793 85.71616948 97.91520814]
  [70.50449964 80.39539317 28.43951956]
  [48.84619024 10.88954027 48.35152924]]

 [[ 3.3180294  98.42031837 15.3246024 ]
  [92.68835059 36.17938659 92.08404505]
  [10.30007893 38.03668129 16.18694889]]

 [[74.0002151  90.19981295 39.20007442]
  [83.49279578 35.23473836 23.91403276]
  [64.31235969 71.30966667 21.75407498]]]
Min: 3.318029395305089, Max: 98.42031836906435


In [6]:
# 5). Create a 3x4 2D array filled with values from 10 to 21 (inclusive).
m = np.arange(start=10, stop=22).reshape(3, 4)
m

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [7]:
# 6). Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.
m = np.arange(start=5, stop=5+10*3, step=3)
print("Length:", m.size)
m

Length: 10


array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [8]:
# 7). Create an arbitrary array of shape (10,10); and find the memory size of this array.
m = np.random.random(size=(10, 10))
print("Size:{}, Itemsize:{}, Memory size:{} bytes".format(m.size, m.itemsize, m.size * m.itemsize))

Size:100, Itemsize:8, Memory size:800 bytes


In [9]:
# 8). Create a null array of size 10 but the fifth value which is 1.
(np.arange(10) == 5-1) * 1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [10]:
# 9). Create an array with values ranging from 10 to 49; and reverse it then (first element becomes last).
np.flip(np.arange(10, 49+1), axis=0)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
# 10). Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and 
    # confirm you can get the same value when you run it next time.
np.random.seed(0)
np.random.uniform(low=0, high=1 - .001, size=(3, 2))

array([[0.54826469, 0.71447418],
       [0.60216061, 0.5443383 ],
       [0.42323114, 0.64524822]])

In [12]:
# 11). Create a 2d 10x10 array with 1 on the border and 0 inside.
m = np.ones(shape=(10, 10))
m[1: -1, 1: -1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# 12). Add a border (filled with 0's) around an existing array:
m = np.ones(shape=(5, 5))
m = np.pad(array=m, pad_width=1)
m

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# 13). Create a 5x5 2D array with values 1,2,3,4,5 on the diagonal
m = np.diag(range(1,6))
m

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [15]:
# 14). Create a 5x5 matrix with row values ranging from 0 to 4
# np.repeat(np.arange(0., 5.), 5).reshape(5,5).T
np.tile(np.arange(0., 5.), 5).reshape(5, 5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [16]:
# 15). Create a random array of size 10 and sort it. 
m = np.random.random(size=10)
m.sort()
m

array([0.07103606, 0.0871293 , 0.38344152, 0.43758721, 0.52889492,
       0.56804456, 0.79172504, 0.891773  , 0.92559664, 0.96366276])

In [17]:
# 1). Find the index of 5th repetition of number 1 in the given array x.
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

it = np.nditer(x, flags=['f_index'])
i = 0; lfi = 5; lf = 1

while not it.finished:
    if lf == it.value:
        i += 1
        if i == lfi:
            print("index of 5th repetition of number 1 is", it.index)
            break

    is_not_finished = it.iternext()

index of 5th repetition of number 1 is 8


In [18]:
# 2). Use arange to get an array [1, 2, 3, ..., 9]. Split x into 3 arrays,
    # each of which has 4, 2, and 3 elements in the original order.
m = np.arange(1, 10)
np.split(m, [4, 4+2])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [19]:
# 3). Use arange to generate the following 2D array:
# [[ 0., 1., 2., 3.],
#  [ 4., 5., 6., 7.],
#  [ 8., 9., 10., 11.],
#  [ 12., 13., 14., 15.]]
m = np.arange(0., 16.).reshape(4, 4)
np.hsplit(m, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [20]:
# 4). Given an 2D array:
# [[5,10,15],
#  [20,25,30],
#  [35,40,45]]
# (1) Slicing to get the sub-array [[10,15], [25,30]]
# (2) Getting individual element value "20"
m = np.arange(5, 46, 5).reshape(3, 3)
print("(1)\n", m[:2, 1:])
print("(2)", m[1, 0])

(1)
 [[10 15]
 [25 30]]
(2) 20


In [21]:
# 5). Let x be an array:
# [[ 1 2 3],
#  [ 4 5 6]].
# and y be an array
# [[ 7 8 9],
#  [10 11 12]].
# Concatenate x and y so that a new array looks like
# [[1, 2, 3, 7, 8, 9],
#  [4, 5, 6, 10, 11, 12]].
x = np.arange(1, 7).reshape(2, 3)
y = np.arange(7, 13).reshape(2, 3)
np.concatenate((x, y), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [22]:
# 6). Compute the min/max (min is divided by max) for each row for a given 2d array,
#     in which integer values range from 1 to 10 [1,10) and shape is (5,3).
# Here requires a random seed to keep the same value from the random generator.
np.random.seed(101)

def func(row):
    return row.min() / row.max()
m = np.random.randint(1, 10 - 0.001, size=(5, 3))
print(m)
np.apply_along_axis(func, axis=1, arr=m)

[[8 4 2]
 [7 8 8]
 [6 4 8]
 [2 6 1]
 [5 8 1]]


array([0.25      , 0.875     , 0.5       , 0.16666667, 0.125     ])

In [23]:
# 7). Normalize a 5x5 random matrix:
#     Tips: a normalization operates like: (the array - the mean)/the standard deviation
np.random.seed(101)

m = np.random.randint(1, 10, size=(5, 5))
print(m, "\nMean:", m.mean(), "Std:", m.std())
(m - m.mean()) / m.std()

[[2 7 8 9 5]
 [9 6 1 6 9]
 [2 4 9 4 4]
 [3 9 4 8 1]
 [8 9 5 4 4]] 
Mean: 5.6 Std: 2.6832815729997477


array([[-1.34164079,  0.52174919,  0.89442719,  1.26710519, -0.2236068 ],
       [ 1.26710519,  0.1490712 , -1.71431878,  0.1490712 ,  1.26710519],
       [-1.34164079, -0.59628479,  1.26710519, -0.59628479, -0.59628479],
       [-0.96896279,  1.26710519, -0.59628479,  0.89442719, -1.71431878],
       [ 0.89442719,  1.26710519, -0.2236068 , -0.59628479, -0.59628479]])

In [24]:
# 8). Convert 3 arrays into a 1d array.
# arr1: 0,1,2
# arr2: 3,4,5,6
# arr3: 7,8,9
# Generate the 3 arrays by numpy arange()
# Desired Output:  ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1 = np.arange(0, 3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

np.hstack((arr1, arr2, arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# 9). Get all items between 15 and 55 from aa, math expression: [15,55].
# The aa is uniformly distributed integers in a 
#     1D array (size=20) with given values (<100). Requires defining a seed.
np.random.seed(101)

aa = np.random.uniform(high=100 - 0.001, size=20)
print(aa)
print()
print("Items between 15 and 55 are:")

aa[(aa >= 15) & (aa <= 55)]

[51.63934637 57.06618802  2.84739417 17.1519941  68.52701289 83.38885237
 30.696315   89.36041436 72.15366463 18.99370548 55.42220488 35.21284327
 18.18905837 78.55939058 96.54735676 23.23513383  8.3560598  60.35423868
 72.89854674 27.62360661]

Items between 15 and 55 are:


array([51.63934637, 17.1519941 , 30.696315  , 18.99370548, 35.21284327,
       18.18905837, 23.23513383, 27.62360661])

In [26]:
# 10). Get the positions where elements of a and b match.

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Positions, matching elements
np.where(a == b), a[np.where(a == b)]

((array([1, 3, 5, 7]),), array([2, 2, 4, 4]))

In [27]:
# 11). Use arange() to create an array from 0 to 20; replace all odd numbers with -1:

m = np.arange(0, 20 + 1)
print(m)
m[m % 2 != 0] = -1
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


In [28]:
# 12). Use two addition functions of Numpy to add every element in a 1D array of size 10;
#     and set a timer to time the two addition functions to see which one is faster.
#      Tips: you can use Jupyter magic command %timeit

x = np.arange(0, 10)
y = np.arange(10, 20)

%timeit x+y
%timeit y+x

662 ns ± 32.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
761 ns ± 117 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
# 13). Use np.put to randomly place 3 numbers (which can be any value, like 5) in a 2D 10x10 zero array:
#         Tips: here, randomly placing 3 numbers means you should first randomly generate the 
#             indices of the 3 numbers in the 2D 10x10 array.

m = np.zeros((10, 10))
for _ in range(3):
    d1 = np.random.randint(0, 10)
    d2 = np.random.randint(0, 10)
    v = np.random.randint(555, 999)
    np.put(m[d1], d2, v)
print(m)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [660.   0.   0.   0.   0.   0.   0.   0.   0. 794.]
 [  0.   0.   0.   0. 654.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


In [30]:
# 14). Subtract the mean of each row of a matrix X. X is a random 2D 5x10 array.
m = np.random.randint(low=0, high=100, size=(5,10))
print(m)
def func(row):
    return (row - row.mean())
print(np.apply_along_axis(func, axis=1, arr=m))

[[28 63  7 10 52 56 38 73 52 18]
 [71 15 44  0 12 17 75 79 97 93]
 [24 36 63 19 35 30 10 60 20 27]
 [ 8 86 26 87 46 47 54 86  9 45]
 [ 2 18 58 92 11 10 94 35 28  3]]
[[-11.7  23.3 -32.7 -29.7  12.3  16.3  -1.7  33.3  12.3 -21.7]
 [ 20.7 -35.3  -6.3 -50.3 -38.3 -33.3  24.7  28.7  46.7  42.7]
 [ -8.4   3.6  30.6 -13.4   2.6  -2.4 -22.4  27.6 -12.4  -5.4]
 [-41.4  36.6 -23.4  37.6  -3.4  -2.4   4.6  36.6 -40.4  -4.4]
 [-33.1 -17.1  22.9  56.9 -24.1 -25.1  58.9  -0.1  -7.1 -32.1]]


In [31]:
# 1) Given a 1d array: [ 3, 6, 9, 25, 10, 8]
m = np.array([3, 6, 9, 25, 10, 8])
print(m)
print("(1) To get all elements except the first:", m[1:])
print("(2) To get all elements except the last:", m[:len(m) - 1])   
print("(3) To get every other element of the array (operation from the first element):", m[::2])
print("(4) To reverse the array:", m[::-1])

[ 3  6  9 25 10  8]
(1) To get all elements except the first: [ 6  9 25 10  8]
(2) To get all elements except the last: [ 3  6  9 25 10]
(3) To get every other element of the array (operation from the first element): [ 3  9 10]
(4) To reverse the array: [ 8 10 25  9  6  3]


In [32]:
# 2) Multidimensional Arrays:
print("(1) create an array with the components as 0-31 and the shape is (8,4).")
m = np.arange(0, 31 + 1).reshape(8, 4)
print(m)
print()

print("(2) set the 3rd element in the 1st row to 0.")
m[0, 2] = 0
print(m)
print()

print("(3) print out the second column.")
print(m[:,1])
print()

print("(4) Get the 3x3 region from the array:")
print(m[2:3+2, range(m.shape[1] - 3, m.shape[1])])
# ([ 9, 10, 11],
#  [13, 14, 15],
#  [17, 18, 19]])

(1) create an array with the components as 0-31 and the shape is (8,4).
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

(2) set the 3rd element in the 1st row to 0.
[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

(3) print out the second column.
[ 1  5  9 13 17 21 25 29]

(4) Get the 3x3 region from the array:
[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [33]:
# 3) Create an 4x4 matrix in which 0 and 1 are staggered, 
# with zeros on the main diagonal. Please use the numpy "slicing" method to realize.
# [[0. 1. 0. 1.]
#  [1. 0. 1. 0.]
#  [0. 1. 0. 1.]
#  [1. 0. 1. 0.]]

m = np.zeros((4, 4))
m[::2, 1::2] = 1
m[1::2, ::2] = 1
print(m)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [34]:
# 1) Given 2 arrays:
# a_2d : [[3,3,3],[4,4,4],[5,5,5]]
# b_1d : [1,2,3]
# Do the subtraction so that the result is:
# [[2 2 2]
#  [2 2 2]
#  [2 2 2]]

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

b_1d = b_1d[..., None]

print(a_2d - b_1d)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [35]:
# 2). Write a 6x6 matrix for multiplication table:

print("by using numpy broadcasting")
x = np.arange(1, 7)
y = np.arange(1, 7).reshape(6, 1)
print(y * x)
print()

print("by using Python nested for-loop")
o = list()
for i in range(1, 7):
    row = list()
    for j in range(1, 7):
        row.append(i * j)
    o.append(row)
o = np.array(o)
print(o)

# Desired output:

# array([[ 1,  2,  3,  4,  5,  6],
#        [ 2,  4,  6,  8, 10, 12],
#        [ 3,  6,  9, 12, 15, 18],
#        [ 4,  8, 12, 16, 20, 24],
#        [ 5, 10, 15, 20, 25, 30],
#        [ 6, 12, 18, 24, 30, 36]])



by using numpy broadcasting
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]

by using Python nested for-loop
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
